import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  progressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 40, // Progress bars a bit higher, X stays lower
    marginHorizontal: 16,
  },
  storyArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    marginBottom: 16,
    marginHorizontal: 16,
  },
  loaderContainer: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  imageLarge: {
    width: 180,
    height: 180,
    borderRadius: 90,
    alignSelf: 'center',
    marginVertical: 10,
  },
  glow: {
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 24,
    elevation: 10,
  },
  pokemonName: {
    fontSize: 28,
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 10,
    letterSpacing: 2,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  infoBlock: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 18,
    padding: 12,
    marginVertical: 8,
    alignItems: 'center',
    width: '100%',
  },
  badge: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 4,
    marginHorizontal: 4,
  },
  badgeText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  container: {
    flex: 1,
    backgroundColor: '#222',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageContainer: {
    alignItems: 'center',
    marginTop: 36,
  },
  infoContainer: {
    marginTop: 24,
    alignItems: 'center',
    marginHorizontal: 16,
  },
  infoLabel: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '600',
    marginTop: 16,
    marginBottom: 4,
    opacity: 0.8,
  },
  badgeRow: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginBottom: 4,
  },
  badgeRowFull: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
    marginBottom: 4,
  },
  typeBadge: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  typeText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
    textTransform: 'capitalize',
  },
  abilityBadge: {
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 4,
  },
  abilityText: {
    color: '#fff',
    fontSize: 14,
    textTransform: 'capitalize',
  },
  closeBtn: {
    position: 'absolute',
    top: 56, // Lowered even more to match new progress bar spacing
    right: 16,
    zIndex: 20,
    backgroundColor: 'rgba(0,0,0,0.16)',
    borderRadius: 20,
    padding: 2,
  },
  loader: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.14)',
    zIndex: 10,
  },
});
